server:
  port: 7100
  servlet:
    session:
      timeout: 10m
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 6MB
  application:
    name: journey-miles-service
  profiles:
    active: dev
  datasource:
    username: myuser
    password: mypass
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/journey_miles_db

config:
  variables:
    pictures:
      users-bucket-name: users-pictures
      destinations-bucket-name: destinations-pictures
  aws:
    region: us-east-1
    accesskey: myaccesskey
    secretkey: mysecretkey
    s3:
      endpoint: "http://localhost:4566"
    dynamodb:
      endpoint: "http://localhost:4566"
