app:
  version: ${APPLICATION_VERSION}
  auth:
    ignorePaths: /healthcheck,/info,/actuator/health,/webjars/**,/swagger-ui.html,/swagger-ui/**,/swagger-resources,/swagger-resources/**,/swagger.yaml,/docs,/v3/api-docs/**
springdoc:
  paths-to-exclude: /swagger-resources/**,/v2/api-docs,/health-check

server:
  port: ${APPLICATION_PORT}
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT}
spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  application:
    name: ${APPLICATION_NAME}
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_HOST}

config:
  security:
    shared-secret: ${SHARED_SECRET_KEY}
    jwt-secret: ${JWT_SEED}
    token-expiration: ${JWT_DURATION}
    refresh-token-expiration: ${REFRESH_TOKEN_DURATION}
  variables:
    pictures:
      users-bucket-name: ${USERS_BUCKET_NAME}
      destinations-bucket-name: ${DESTINATIONS_BUCKET_NAME}
  aws:
    region: ${AWS_REGION}
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}
    s3:
      endpoint: ${S3_ENDPOINT}
    dynamodb:
      endpoint: ${DYNAMODB_ENDPOINT}
