package com.study.alura.challenge.journeymiles.model.enums

enum class ErrorCodeEnum(val code: Int) {
    TESTIMONIAL_NOT_FOUND_ERROR(1001),
    USER_NOT_RELATED_TO_TESTIMONIAL_ERROR(1002),
    DESTINATION_NOT_FOUND_ERROR(2001),
    USER_NOT_FOUND_ERROR(3001),
    USER_NOT_FOUND_BY_EMAIL_ERROR(3002),
    USERNAME_NOT_PROVIDED_ERROR(3003),
    USERNAME_ALREADY_EXISTS_ERROR(3004),
    UNSUPPORTED_PICTURE_TYPE_ERROR(4001),
    PICTURE_NOT_FOUND_ERROR(8001),
    PICTURE_ALREADY_PRESENT_ERROR(8002),
    GENERIC_ERROR(9001),
    VALIDATION_ERROR(9002),
    BAD_CREDENTIALS_ERROR(9003),
    AUTHENTICATION_NOT_PRESENT_ERROR(9004),
    EXPIRED_REFRESH_TOKEN_ERROR(9005),
    EXPIRED_TOKEN_ERROR(9007),
    ;
}