CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL,
    name VARCHAR(100) NOT NULL,
    password TEXT NOT NULL,
    email VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

ALTER TABLE testimonials ADD user_id BIGINT DEFAULT NULL;